### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by djsimoneau** [taylorfsteele/MarsRover#2]
![image](https://user-images.githubusercontent.com/15616714/92232215-2a39ae00-ee7c-11ea-89aa-0d8f5fa85acf.png)

**Comment by taylorfsteele** [comment]
Thanks a ton for the review. I changed the typing like you suggested on createRover.ts, this isn't giving any errors in the compiler.
```
const parseLocationValues = (startingPosition: string): RoverStartingPosition => {
  const locationValues = {
    x: parseInt(startingPosition.split(" ")[0]),
    y: parseInt(startingPosition.split(" ")[1]),
    orientation: startingPosition.split(" ")[2] as CardinalDirections,
  };

  return locationValues;
};
```

Previously I was casting `locationValues` as the `RoverStartingPosition` type.

The Record utility was a perfect fit for the implementation of the cardinal dictionary. The intent was to use that dictionary as the source of instructions for the rover, and the Record type works great for that. Thanks!
